package dss.g22.business;

public enum Operacao {
	REGISTAR_DESPESA,
	ALTERAR_DESPESA,
	REMOVER_DESPESA,
	REGISTAR_FATURA,
	ALTERAR_FATURA,
	REMOVER_FATURA,
	ADICIONAR_TRANSFERENCIA,
	REMOVER_TRANSFERENCIA,
	REGISTAR_MORADOR,
	ELIMINAR_MORADOR
}