/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static dss.g22.presentation.images.ConstantesImagens.ALTURA_IMG_NORMAL;
import static dss.g22.presentation.images.ConstantesImagens.LARGURA_IMG_NORMAL;

/**
 *
 * @author joao
 */
public class DialogRegisto extends javax.swing.JDialog {
    
    /**
     * Creates new form DialogRegisto
     */
    public DialogRegisto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selecionadorImagem = new javax.swing.JFileChooser();
        labelNome = new javax.swing.JLabel();
        labelRegistoEmail = new javax.swing.JLabel();
        labelRegistoPassword = new javax.swing.JLabel();
        labelConfirmarPassword = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoRegistoEmail = new javax.swing.JTextField();
        campoRegistoPassword = new javax.swing.JPasswordField();
        campoConfirmarPassword = new javax.swing.JPasswordField();
        butaoCancelar = new javax.swing.JButton();
        butaoRegistar = new javax.swing.JButton();
        butaoProcurar = new javax.swing.JButton();
        labelImagemMorador = new javax.swing.JLabel();

        selecionadorImagem.setAcceptAllFileFilterUsed(false);
        selecionadorImagem.setCurrentDirectory(null);
        selecionadorImagem.setDialogTitle("Selecionar imagem");
        selecionadorImagem.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Imagens", javax.imageio.ImageIO.getReaderFileSuffixes()));

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(490, 295));
    setPreferredSize(new java.awt.Dimension(490, 295));
    setResizable(false);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    labelNome.setText("Nome:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(labelNome, gridBagConstraints);

    labelRegistoEmail.setText("E-mail:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(labelRegistoEmail, gridBagConstraints);

    labelRegistoPassword.setText("Password:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(labelRegistoPassword, gridBagConstraints);

    labelConfirmarPassword.setText("Confirmar password:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(labelConfirmarPassword, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(campoNome, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(campoRegistoEmail, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(campoRegistoPassword, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(campoConfirmarPassword, gridBagConstraints);

    butaoCancelar.setText("Cancelar");
    butaoCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            butaoCancelarActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    getContentPane().add(butaoCancelar, gridBagConstraints);

    butaoRegistar.setText("Registar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    getContentPane().add(butaoRegistar, gridBagConstraints);

    butaoProcurar.setText("Procurar...");
    butaoProcurar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            butaoProcurarActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
    getContentPane().add(butaoProcurar, gridBagConstraints);

    labelImagemMorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dss/g22/presentation/images/NoImage.jpeg"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
    getContentPane().add(labelImagemMorador, gridBagConstraints);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_butaoCancelarActionPerformed

    private void butaoProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoProcurarActionPerformed
        int r = selecionadorImagem.showOpenDialog(this);

        if(r == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage imgMorador = ImageIO.read(selecionadorImagem.getSelectedFile());
                final int l = imgMorador.getWidth(), h = imgMorador.getHeight();
                ImageIcon iconImgMorador;

                if(l != LARGURA_IMG_NORMAL || h != ALTURA_IMG_NORMAL) {
                    iconImgMorador = new ImageIcon(
                        imgMorador.getScaledInstance(LARGURA_IMG_NORMAL, ALTURA_IMG_NORMAL, Image.SCALE_SMOOTH)
                    );
                } else {
                    iconImgMorador = new ImageIcon(imgMorador);
                }

                labelImagemMorador.setIcon(iconImgMorador);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_butaoProcurarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoCancelar;
    private javax.swing.JButton butaoProcurar;
    private javax.swing.JButton butaoRegistar;
    private javax.swing.JPasswordField campoConfirmarPassword;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoRegistoEmail;
    private javax.swing.JPasswordField campoRegistoPassword;
    private javax.swing.JLabel labelConfirmarPassword;
    private javax.swing.JLabel labelImagemMorador;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRegistoEmail;
    private javax.swing.JLabel labelRegistoPassword;
    private javax.swing.JFileChooser selecionadorImagem;
    // End of variables declaration//GEN-END:variables
}
