/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

/**
 *
 * @author joao
 */
public class DialogRegistarDespesa extends javax.swing.JDialog {
    
    /**
     * Creates new form DialogRegistarDespesa
     */
    public DialogRegistarDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelBotoes = new javax.swing.JPanel();
        botaoCancelar = new javax.swing.JButton();
        botaoAnterior = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        iconeDespesa = new javax.swing.JLabel();
        labelNomeDespesa = new javax.swing.JLabel();
        campoNomeDespesa = new javax.swing.JTextField();
        labelDescricaoDespesa = new javax.swing.JLabel();
        scrollDescricaoDespesa = new javax.swing.JScrollPane();
        areaTextoDescricao = new javax.swing.JTextArea();
        labelErroNomeObrigatorio = new javax.swing.JLabel();
        opcoesPeriodicidade = new javax.swing.JComboBox<>();
        labelOcorre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar despesa");
        setMinimumSize(new java.awt.Dimension(420, 470));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("registarDespesa"); // NOI18N
        setPreferredSize(new java.awt.Dimension(420, 465));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painelBotoes.setLayout(new javax.swing.BoxLayout(painelBotoes, javax.swing.BoxLayout.LINE_AXIS));

        botaoCancelar.setText("Cancelar");
        painelBotoes.add(botaoCancelar);

        botaoAnterior.setText("Anterior");
        botaoAnterior.setEnabled(false);
        botaoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnteriorActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoAnterior);

        jButton3.setText("Seguinte");
        painelBotoes.add(jButton3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(painelBotoes, gridBagConstraints);

        iconeDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dss/g22/presentation/images/ExpenseIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 10, 0);
        getContentPane().add(iconeDespesa, gridBagConstraints);

        labelNomeDespesa.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelNomeDespesa, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 0);
        getContentPane().add(campoNomeDespesa, gridBagConstraints);

        labelDescricaoDespesa.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelDescricaoDespesa, gridBagConstraints);

        areaTextoDescricao.setColumns(30);
        areaTextoDescricao.setLineWrap(true);
        areaTextoDescricao.setRows(6);
        areaTextoDescricao.setTabSize(4);
        areaTextoDescricao.setWrapStyleWord(true);
        scrollDescricaoDespesa.setViewportView(areaTextoDescricao);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 4);
        getContentPane().add(scrollDescricaoDespesa, gridBagConstraints);

        labelErroNomeObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErroNomeObrigatorio.setText("A despesa tem de ter um nome.");
        labelErroNomeObrigatorio.setOpaque(true);
        labelErroNomeObrigatorio.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(labelErroNomeObrigatorio, gridBagConstraints);

        opcoesPeriodicidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pontualmente", "Diariamente", "Semanalmente", "Quinzenalmente", "Mensalmente" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 0, 0);
        getContentPane().add(opcoesPeriodicidade, gridBagConstraints);

        labelOcorre.setText("Ocorre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelOcorre, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAnteriorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoDescricao;
    private javax.swing.JButton botaoAnterior;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JTextField campoNomeDespesa;
    private javax.swing.JLabel iconeDespesa;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel labelDescricaoDespesa;
    private javax.swing.JLabel labelErroNomeObrigatorio;
    private javax.swing.JLabel labelNomeDespesa;
    private javax.swing.JLabel labelOcorre;
    private javax.swing.JComboBox<String> opcoesPeriodicidade;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JScrollPane scrollDescricaoDespesa;
    // End of variables declaration//GEN-END:variables
}
