/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

/**
 *
 * @author joao
 */
public class DialogDadosDespesa extends javax.swing.JDialog {

    /**
     * Creates new form DialogDadosDespesa
     */
    public DialogDadosDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNomeDespesa = new javax.swing.JLabel();
        campoNomeDespesa = new javax.swing.JTextField();
        labelDescricaoDespesa = new javax.swing.JLabel();
        scrollDescricaoDespesa = new javax.swing.JScrollPane();
        areaTextoDescricao = new javax.swing.JTextArea();
        iconeDespesa = new javax.swing.JLabel();
        labelErroNomeObrigatorio = new javax.swing.JLabel();
        painelBotoesCancelarRegistar = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        butaoCancelarRegistoDespesa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botaoDadosAdicionais = new javax.swing.JButton();
        opcoesPeriodicidade = new javax.swing.JComboBox<>();
        labelOcorre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNomeDespesa.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(labelNomeDespesa, gridBagConstraints);

        campoNomeDespesa.setText("Luz");
        campoNomeDespesa.setEnabled(false);
        campoNomeDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeDespesaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 0);
        getContentPane().add(campoNomeDespesa, gridBagConstraints);

        labelDescricaoDespesa.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelDescricaoDespesa, gridBagConstraints);

        areaTextoDescricao.setEditable(false);
        areaTextoDescricao.setColumns(30);
        areaTextoDescricao.setLineWrap(true);
        areaTextoDescricao.setRows(6);
        areaTextoDescricao.setTabSize(4);
        areaTextoDescricao.setText("Depesa da luz");
        areaTextoDescricao.setWrapStyleWord(true);
        areaTextoDescricao.setEnabled(false);
        scrollDescricaoDespesa.setViewportView(areaTextoDescricao);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 4);
        getContentPane().add(scrollDescricaoDespesa, gridBagConstraints);

        iconeDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dss/g22/presentation/images/ExpenseIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(iconeDespesa, gridBagConstraints);

        labelErroNomeObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErroNomeObrigatorio.setText("A despesa tem de ter um nome.");
        labelErroNomeObrigatorio.setOpaque(true);
        labelErroNomeObrigatorio.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(labelErroNomeObrigatorio, gridBagConstraints);

        painelBotoesCancelarRegistar.setLayout(new java.awt.GridBagLayout());

        jToggleButton2.setText("Ativar edição");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        painelBotoesCancelarRegistar.add(jToggleButton2, gridBagConstraints);

        butaoCancelarRegistoDespesa.setText("Desfazer alterações");
        butaoCancelarRegistoDespesa.setEnabled(false);
        butaoCancelarRegistoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCancelarRegistoDespesaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        painelBotoesCancelarRegistar.add(butaoCancelarRegistoDespesa, gridBagConstraints);

        jButton1.setText("Submeter");
        jButton1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        painelBotoesCancelarRegistar.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(painelBotoesCancelarRegistar, gridBagConstraints);

        botaoDadosAdicionais.setText("Adicionar fatura");
        botaoDadosAdicionais.setEnabled(false);
        botaoDadosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDadosAdicionaisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        getContentPane().add(botaoDadosAdicionais, gridBagConstraints);

        opcoesPeriodicidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pontualmente", "Diariamente", "Semanalmente", "Quinzenalmente", "Mensalmente" }));
        opcoesPeriodicidade.setEnabled(false);
        opcoesPeriodicidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoesPeriodicidadeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 0, 0);
        getContentPane().add(opcoesPeriodicidade, gridBagConstraints);

        labelOcorre.setText("Ocorre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelOcorre, gridBagConstraints);

        jLabel1.setText("Fatura(s) paga(s):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12/11/2016", "12/12/2016", "12/1/2017", "12/2/2017" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setVisibleRowCount(4);
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeDespesaActionPerformed

    private void butaoCancelarRegistoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCancelarRegistoDespesaActionPerformed
        dispose();
    }//GEN-LAST:event_butaoCancelarRegistoDespesaActionPerformed

    private void botaoDadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDadosAdicionaisActionPerformed
        if(botaoDadosAdicionais.getText().equals("Associar fatura")) {
            DialogDadosFatura dialogDadosFatura = new DialogDadosFatura(this, true);

            dialogDadosFatura.setLocationRelativeTo(this);
            dialogDadosFatura.setVisible(true);
        } else {
            // COMPLETAR
        }
    }//GEN-LAST:event_botaoDadosAdicionaisActionPerformed

    private void opcoesPeriodicidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoesPeriodicidadeActionPerformed
        String opcao = (String) opcoesPeriodicidade.getSelectedItem();

        if(opcao.equals("Pontualmente"))
        botaoDadosAdicionais.setText("Associar fatura");
        else
        botaoDadosAdicionais.setText("Definir método de divisão");
    }//GEN-LAST:event_opcoesPeriodicidadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoDescricao;
    private javax.swing.JButton botaoDadosAdicionais;
    private javax.swing.JButton butaoCancelarRegistoDespesa;
    private javax.swing.JTextField campoNomeDespesa;
    private javax.swing.JLabel iconeDespesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel labelDescricaoDespesa;
    private javax.swing.JLabel labelErroNomeObrigatorio;
    private javax.swing.JLabel labelNomeDespesa;
    private javax.swing.JLabel labelOcorre;
    private javax.swing.JComboBox<String> opcoesPeriodicidade;
    private javax.swing.JPanel painelBotoesCancelarRegistar;
    private javax.swing.JScrollPane scrollDescricaoDespesa;
    // End of variables declaration//GEN-END:variables
}
