/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

import dss.g22.business.Facade;
import dss.g22.business.moradores.CampoInvalidoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author joaop
 */
public class DialogConfirmarApagarConta extends javax.swing.JDialog {

    Facade facade;

    /**
     * Creates new form ConfirmarApagarConta
     */
    public DialogConfirmarApagarConta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.facade = facade;
        initComponents();
    }

    public DialogConfirmarApagarConta(java.awt.Frame parent, boolean modal, Facade facade) {
        super(parent, modal);
        this.facade = facade;
        initComponents();
    }

    public DialogConfirmarApagarConta(javax.swing.JDialog parent, boolean modal, Facade facade) {
        super(parent, modal);
        this.facade = facade;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        campoPassword = new javax.swing.JPasswordField();
        labelIntroduzaPassword = new javax.swing.JLabel();
        labelErro = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        butaoCancelar = new javax.swing.JButton();
        butaoConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmar remoção de conta de morador");
        setMinimumSize(new java.awt.Dimension(440, 140));
        setPreferredSize(new java.awt.Dimension(440, 140));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        campoPassword.setPreferredSize(new java.awt.Dimension(376, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        getContentPane().add(campoPassword, gridBagConstraints);

        labelIntroduzaPassword.setText("Introduza a password para confirmar a eliminaçao da conta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(labelIntroduzaPassword, gridBagConstraints);

        labelErro.setForeground(new java.awt.Color(255, 0, 0));
        labelErro.setText("A password que introduziu este errada");
        labelErro.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(labelErro, gridBagConstraints);

        painelBotoes.setLayout(new javax.swing.BoxLayout(painelBotoes, javax.swing.BoxLayout.LINE_AXIS));

        butaoCancelar.setText("Cancelar");
        butaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCancelarActionPerformed(evt);
            }
        });
        painelBotoes.add(butaoCancelar);

        butaoConfirmar.setText("Confirmar");
        butaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoConfirmarActionPerformed(evt);
            }
        });
        painelBotoes.add(butaoConfirmar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(painelBotoes, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoConfirmarActionPerformed
        String password = new String(campoPassword.getPassword());

        try {
            facade.eliminaContaMoradorAutenticado(password);
            JDialog dialogGestaoContaMorador = (JDialog) getParent();
            JFrame dashboard = (JFrame) dialogGestaoContaMorador.getParent();

            dispose();
            dialogGestaoContaMorador.dispose();
            dashboard.dispose();
            (new Login(facade)).setVisible(true);
        } catch (CampoInvalidoException ex) {
            labelErro.setVisible(true);
        }
    }//GEN-LAST:event_butaoConfirmarActionPerformed

    private void butaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_butaoCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoCancelar;
    private javax.swing.JButton butaoConfirmar;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelIntroduzaPassword;
    private javax.swing.JPanel painelBotoes;
    // End of variables declaration//GEN-END:variables
}
