/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

/**
 *
 * @author joao
 */
public class DialogAlterarPassword extends javax.swing.JDialog {

    /**
     * Creates new form DialogAlterarPassword
     */
    public DialogAlterarPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DialogAlterarPassword(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPasswordAtual = new javax.swing.JLabel();
        campoPasswordAtual = new javax.swing.JPasswordField();
        labelNovaPassword = new javax.swing.JLabel();
        campoNovaPassword = new javax.swing.JTextField();
        labelErroPassDiferentes = new javax.swing.JLabel();
        botaoOk = new javax.swing.JButton();
        labelConfirmarNovaPassword = new javax.swing.JLabel();
        campoConfirmarNovaPassword = new javax.swing.JTextField();
        labelPasswordInvalida = new javax.swing.JLabel();
        labelPasswordInvalida.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelPasswordAtual.setText("Password atual:");

        labelNovaPassword.setText("Nova password:");

        labelErroPassDiferentes.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        labelErroPassDiferentes.setText("As passwords introduzidas não coincidem");
        labelErroPassDiferentes.setOpaque(true);
        labelErroPassDiferentes.setVisible(false);

        botaoOk.setText("Ok");

        labelConfirmarNovaPassword.setText("Confirmar nova password:");

        labelPasswordInvalida.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        labelPasswordInvalida.setText("Password inválida");
        labelPasswordInvalida.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPasswordAtual)
                            .addComponent(campoPasswordAtual)
                            .addComponent(labelNovaPassword)
                            .addComponent(campoNovaPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPasswordInvalida))
                    .addComponent(labelConfirmarNovaPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoOk)
                            .addComponent(campoConfirmarNovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErroPassDiferentes)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPasswordAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPasswordAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPasswordInvalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNovaPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConfirmarNovaPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoConfirmarNovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErroPassDiferentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoConfirmarNovaPassword;
    private javax.swing.JTextField campoNovaPassword;
    private javax.swing.JPasswordField campoPasswordAtual;
    private javax.swing.JLabel labelConfirmarNovaPassword;
    private javax.swing.JLabel labelErroPassDiferentes;
    private javax.swing.JLabel labelNovaPassword;
    private javax.swing.JLabel labelPasswordAtual;
    private javax.swing.JLabel labelPasswordInvalida;
    // End of variables declaration//GEN-END:variables
}
