/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

/**
 *
 * @author joao
 */
public class DialogAlterarEmail extends javax.swing.JDialog {

    /**
     * Creates new form DialogAlterarEmail
     */
    public DialogAlterarEmail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DialogAlterarEmail(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNovoEmail = new javax.swing.JLabel();
        campoNovoEmail = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        labelErroEmailExiste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar e-mail");
        setMinimumSize(new java.awt.Dimension(410, 135));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("alterarEmail"); // NOI18N
        setPreferredSize(new java.awt.Dimension(405, 145));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNovoEmail.setText("Novo e-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(labelNovoEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(campoNovoEmail, gridBagConstraints);

        botaoConfirmar.setText("Confirmar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(botaoConfirmar, gridBagConstraints);

        labelErroEmailExiste.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        labelErroEmailExiste.setText("O e-mail escolhido já está a ser usado por outro morador");
        labelErroEmailExiste.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(labelErroEmailExiste, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JTextField campoNovoEmail;
    private javax.swing.JLabel labelErroEmailExiste;
    private javax.swing.JLabel labelNovoEmail;
    // End of variables declaration//GEN-END:variables
}
