/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dss.g22.presentation;

/**
 *
 * @author joao
 */
public class PainelContaCorrente extends javax.swing.JPanel {

    /**
     * Creates new form painelContaCorrente
     */
    public PainelContaCorrente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollTabelaCC = new javax.swing.JScrollPane();
        tabelaMovimentosContaCorrente = new javax.swing.JTable();
        painelPesquisaCC = new javax.swing.JPanel();
        labelTermoPesquisaCC = new javax.swing.JLabel();
        campoTermoPesquisaCC = new javax.swing.JTextField();
        labelDataInicioCC = new javax.swing.JLabel();
        selecionadorDataInicioCC = new com.github.lgooddatepicker.components.DatePicker();
        labelDataFimCC = new javax.swing.JLabel();
        selecionadorDataFimCC = new com.github.lgooddatepicker.components.DatePicker();
        butaoPesquisaCC = new javax.swing.JButton();

        tabelaMovimentosContaCorrente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Data", "Descrição", "Débito", "Crédito", "Saldo após mov."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaMovimentosContaCorrente.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        scrollTabelaCC.setViewportView(tabelaMovimentosContaCorrente);
        if (tabelaMovimentosContaCorrente.getColumnModel().getColumnCount() > 0) {
            tabelaMovimentosContaCorrente.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaMovimentosContaCorrente.getColumnModel().getColumn(2).setPreferredWidth(25);
            tabelaMovimentosContaCorrente.getColumnModel().getColumn(3).setPreferredWidth(25);
            tabelaMovimentosContaCorrente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        painelPesquisaCC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelPesquisaCC.setLayout(new java.awt.GridBagLayout());

        labelTermoPesquisaCC.setText("Termo de pesquisa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        painelPesquisaCC.add(labelTermoPesquisaCC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 2);
        painelPesquisaCC.add(campoTermoPesquisaCC, gridBagConstraints);

        labelDataInicioCC.setText("Data de início:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        painelPesquisaCC.add(labelDataInicioCC, gridBagConstraints);

        selecionadorDataInicioCC.setToolTipText("Data de início");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        painelPesquisaCC.add(selecionadorDataInicioCC, gridBagConstraints);

        labelDataFimCC.setText("Data de fim:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        painelPesquisaCC.add(labelDataFimCC, gridBagConstraints);

        selecionadorDataFimCC.setToolTipText("Data de fim");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        painelPesquisaCC.add(selecionadorDataFimCC, gridBagConstraints);

        butaoPesquisaCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dss/g22/presentation/images/SearchIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        painelPesquisaCC.add(butaoPesquisaCC, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPesquisaCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTabelaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabelaCC, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoPesquisaCC;
    private javax.swing.JTextField campoTermoPesquisaCC;
    private javax.swing.JLabel labelDataFimCC;
    private javax.swing.JLabel labelDataInicioCC;
    private javax.swing.JLabel labelTermoPesquisaCC;
    private javax.swing.JPanel painelPesquisaCC;
    private javax.swing.JScrollPane scrollTabelaCC;
    private com.github.lgooddatepicker.components.DatePicker selecionadorDataFimCC;
    private com.github.lgooddatepicker.components.DatePicker selecionadorDataInicioCC;
    private javax.swing.JTable tabelaMovimentosContaCorrente;
    // End of variables declaration//GEN-END:variables
}
